name: Moonshot
favicon: null
layout_spectrum: 0.41156485793180764
typography_spectrum: 0.5795320393517613
title: Moonshot Podcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010206'
    - '#234258'
    - '#4c7082'
    - '#979a8f'
    - '#bab9a8'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
